language: php
php:
  - 7.2
  - 7.3

install:
  - composer require "phpunit/phpunit:8.*"
#before_script:
#  - pecl install -f proctitle
#  - phpenv config-add travisphp.ini
script: ./vendor/bin/phpunit 

