language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer require "phpunit/phpunit:4.0.*"
#before_script:
#  - pecl install -f proctitle
#  - phpenv config-add travisphp.ini
script: ./vendor/bin/phpunit 

