language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2

install:
  - composer require "phpunit/phpunit:8.*"
#before_script:
#  - pecl install -f proctitle
#  - phpenv config-add travisphp.ini
script: ./vendor/bin/phpunit 

